do81818/project_iruri

src/main/webapp/WEB-INF/views/mypage_trainer.jsp, src/test/java/com/iruri/ex/database/DataSourceTest.java
테스트입니다.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Mypage trainer_jsp

src/main/webapp/WEB-INF/views/home.jsp, src/test/java/com/iruri/ex/database/DataSourceTest.java
- 테스트입니다
- home.jsp 변경해봤습니다
- 내용을 적어주세요.
=> Challenge_test입니다

src/main/webapp/WEB-INF/views/home2.jsp, src/test/java/com/iruri/ex/database/DataSourceTest.java
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Mypage admin

src/main/java/com/iruri/ex/Service/IClassService.java, src/main/java/com/iruri/ex/Service/IClassServiceImpl.java, src/main/java/com/iruri/ex/Service/IUserService.java, src/main/java/com/iruri/ex/Service/IUserServleImpl.java, src/main/java/com/iruri/ex/controller/MainController.java, src/main/java/com/iruri/ex/controller/MypageTrainerController.java, src/main/java/com/iruri/ex/mapper/IClassMapper.java, src/main/java/com/iruri/ex/mapper/IUserMapper.java, src/main/java/com/iruri/ex/vo/IClassVO.java, src/main/resources/com/iruri/ex/mapper/IClassMapper.xml, src/main/resources/com/iruri/ex/mapper/IUserMapper.xml, src/main/webapp/WEB-INF/views/include/static.jsp, src/main/webapp/WEB-INF/views/mypage_trainer.jsp, src/main/webapp/WEB-INF/views/mypage_trainer/JSP작성 템플릿.jsp, src/main/webapp/WEB-INF/views/mypage_trainer/mypage_trainer_main.jsp, src/main/webapp/WEB-INF/views/헤더카테고리.html, src/main/webapp/resources/src/css/component/card.css, src/main/webapp/resources/src/css/component/paging.css, src/main/webapp/resources/src/css/page/mypage_trainer.css, src/main/webapp/resources/src/css/styles.css
- 마이페이지 트레이너 메인페이지 작성 중
- 마이페이지 트레이너 메인페이지 작성 중
- 내용을 적어주세요.
=> 마이페이지 트레이너 메인페이지 작성 중

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/java/com/iruri/ex/mapper/IClassMapper.java, src/main/java/com/iruri/ex/mapper/IUserInfoMapper.java, src/main/java/com/iruri/ex/mapper/IUserMapper.java, src/main/java/com/iruri/ex/service/IClassService.java, src/main/java/com/iruri/ex/service/IClassServiceImpl.java, src/main/java/com/iruri/ex/service/IUserInfoService.java, src/main/java/com/iruri/ex/service/IUserInfoServleImpl.java, src/main/java/com/iruri/ex/service/IUserService.java, src/main/java/com/iruri/ex/service/IUserServleImpl.java, src/main/java/com/iruri/ex/vo/IClassVO.java, src/main/java/com/iruri/ex/vo/IUserInfoVO.java, src/main/resources/com/iruri/ex/mapper/IClassMapper.xml, src/main/resources/com/iruri/ex/mapper/IUserInfoMapper.xml, src/main/resources/com/iruri/ex/mapper/IUserMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/resources/src/js/mypage_user_chart.js
- 내용을 적어주세요.
- 현재 수강중인 클래스 리스트 갯수와 몸무게 그래프 수정중 입니다. 
- 내용을 적어주세요.
=> mypage 클래스 갯수, 몸무게 그래프 수정중

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/java/com/iruri/ex/mapper/IClassMapper.java, src/main/java/com/iruri/ex/mapper/IUserInfoMapper.java, src/main/java/com/iruri/ex/mapper/IUserMapper.java, src/main/java/com/iruri/ex/service/IClassService.java, src/main/java/com/iruri/ex/service/IClassServiceImpl.java, src/main/java/com/iruri/ex/service/IUserInfoService.java, src/main/java/com/iruri/ex/service/IUserInfoServleImpl.java, src/main/java/com/iruri/ex/service/IUserService.java, src/main/java/com/iruri/ex/service/IUserServleImpl.java, src/main/java/com/iruri/ex/vo/IClassVO.java, src/main/java/com/iruri/ex/vo/IUserInfoVO.java, src/main/resources/com/iruri/ex/mapper/IClassMapper.xml, src/main/resources/com/iruri/ex/mapper/IUserInfoMapper.xml, src/main/resources/com/iruri/ex/mapper/IUserMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/resources/src/js/mypage_user_chart.js
Reverts do81818/project_iruri#17
=> Revert "mypage 클래스 갯수, 몸무게 그래프 수정중"

src/main/java/com/iruri/ex/controller/MypageAdminController.java, src/main/java/com/iruri/ex/mapper/AdminMapper.java, src/main/java/com/iruri/ex/service/ReportService.java, src/main/java/com/iruri/ex/service/ReportServiceImpl.java, src/main/java/com/iruri/ex/vo/ReportVO.java, src/main/resources/com/iruri/ex/mapper/AdminMapper.xml, src/main/webapp/WEB-INF/views/mypage_admin/list.jsp, src/main/webapp/WEB-INF/views/mypage_admin/mypage_admin.jsp, src/main/webapp/WEB-INF/views/mypage_admin/mypage_admin_memberBlackList.jsp, src/main/webapp/WEB-INF/views/mypage_admin/mypage_admin_memberlist.jsp, src/main/webapp/resources/src/css/admin/admin_main_normalMember.css, src/main/webapp/resources/src/js/admin_main.js
관리자 마이페이지 메인 회원관리> 신고알림 리스트 페이징까지 작업
=> 0728_mypage_admin

src/main/java/com/iruri/ex/controller/MypageAdminController.java, src/main/java/com/iruri/ex/page/PageVO.java, src/main/webapp/WEB-INF/views/mypage_admin/mypage_admin.jsp, src/main/webapp/WEB-INF/views/mypage_admin/mypage_admin2.jsp
관리자 메인 회원관리> 신고알림 ajax 페이징까지 완료
ajax로 리스트 추출 및 페이징 작업
_ 페이지 amount 개념 확립
=> 2021.07.29 관리자 메인 회원관리> 신고알림 ajax 페이징까지 완료

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/java/com/iruri/ex/mapper/BoardMapper.java, src/main/java/com/iruri/ex/mapper/IClassMapper.java, src/main/java/com/iruri/ex/mapper/PointMapper.java, src/main/java/com/iruri/ex/service/BoardService.java, src/main/java/com/iruri/ex/service/BoardServiceImpl.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/java/com/iruri/ex/service/IClassService.java, src/main/java/com/iruri/ex/service/IClassServiceImpl.java, src/main/java/com/iruri/ex/service/PointService.java, src/main/java/com/iruri/ex/service/PointServiceImpl.java, src/main/java/com/iruri/ex/vo/BoardVO.java, src/main/java/com/iruri/ex/vo/PointVO.java, src/main/resources/com/iruri/ex/mapper/BoardMapper.xml, src/main/resources/com/iruri/ex/mapper/IClassMapper.xml, src/main/resources/com/iruri/ex/mapper/PointMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_boardlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_challengelist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_pointlist.jsp, src/main/webapp/resources/src/css/page/mypage_user_boardlist.css, src/main/webapp/resources/src/css/page/mypage_user_challengelist.css, src/main/webapp/resources/src/css/page/mypage_user_main.css, src/main/webapp/resources/src/css/page/mypage_user_pointlist.css, src/main/webapp/resources/src/css/styles.css
mypage_user 보드, 포인트페이징완료
carousel slide
- 내용을 적어주세요.
=> mypage_user 보드, 포인트페이징완료

src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/page/Criteria.java, src/main/java/com/iruri/ex/page/PageVO.java, src/main/java/com/iruri/ex/page/SearchCriteria.java, src/main/java/com/iruri/ex/service/ChallengeService.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/java/com/iruri/ex/vo/LikeListVO.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/views/challenge/challenge_endList.jsp
- 210802 관심챌린지 로그인 후 정보 받아오기
- 210802 관심챌린지 로그인 후 정보 받아오기
- 내용을 적어주세요.
=> 210802 관심챌린지 로그인 후 정보 받아오기

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_boardlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_challengelist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_pointlist.jsp, src/main/webapp/resources/src/css/page/mypage_user_challengelist.css
-mypage_user 챌린지 페이지 수정중
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Mypage user2

src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/page/Criteria.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/views/challenge/challenge_LikeList.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_before.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_endList.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_main2.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_make_form.jsp, src/main/webapp/resources/src/css/page/c_detail_before_styles.css, src/main/webapp/resources/src/css/page/c_main_styles.css
- 210804 - 검색기능 구현하기, 챌린지 개설 폼/검색 기록 없애기, 지난챌린지 안내버튼, 셀렉트박스 정렬
- 210804 - 검색기능 구현하기, 챌린지 개설 폼/검색 기록 없애기, 지난챌린지 안내버튼, 셀렉트박스 정렬
- 내용을 적어주세요.
=> 210804 - 검색기능 구현하기, 챌린지 개설 폼/검색 기록 없애기, 지난챌린지 안내버튼, 셀렉트박스 정렬

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/java/com/iruri/ex/mapper/UserChallengeMapper.java, src/main/java/com/iruri/ex/page/Criteria.java, src/main/java/com/iruri/ex/service/UserChallengeService.java, src/main/java/com/iruri/ex/service/UserChallengeServiceImpl.java, src/main/java/com/iruri/ex/vo/BuyVO.java, src/main/java/com/iruri/ex/vo/PayVO.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/resources/com/iruri/ex/mapper/UserChallengeMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_challengelist.jsp, src/main/webapp/resources/src/css/page/mypage_user_challengelist.css
mypage_user 챌린지 페이지 ajax 페이징 성공 하지만 밑에 하나더 해야함
mypage_user 챌린지 페이지 ajax 페이징 성공 하지만 밑에 하나더 해야함
- 내용을 적어주세요.
=> mypage_user 챌린지 페이지 ajax 페이징 성공 하지만 밑에 하나더 해야함

src/main/java/com/iruri/ex/controller/MypageTrainerController.java, src/main/java/com/iruri/ex/mapper/MypageTrainerMapper.java, src/main/java/com/iruri/ex/service/MypageTrainerService.java, src/main/java/com/iruri/ex/service/MypageTrainerServiceImpl.java, src/main/java/com/iruri/ex/vo/BuyVO.java, src/main/java/com/iruri/ex/vo/PayVO.java, src/main/resources/com/iruri/ex/mapper/MypageTrainerMapper.xml, src/main/webapp/WEB-INF/views/mypage_trainer/mypage_trainer_profit.jsp
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> 이달의 수익 출력 완

src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/service/ChallengeService.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/views/challenge/challenge_LikeList.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_after.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_before.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_endList.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_main2.jsp, src/main/webapp/resources/src/css/page/c_detail_after_styles.css
- 210807 - 관심챌린지 하트 눌린거 유지, 지난 챌린지 하트 안눌리게하기, 상세페이지 참여 후 댓글 페이징,ajax
- 210807 - 관심챌린지 하트 눌린거 유지, 지난 챌린지 하트 안눌리게하기, 상세페이지 참여 후 댓글 페이징,ajax
- 내용을 적어주세요.
=> 210807 - 관심챌린지 하트 눌린거 유지, 지난 챌린지 하트 안눌리게하기, 상세페이지 참여 후 댓글 페이징,ajax

src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/controller/MypageTrainerController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/service/ChallengeService.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/java/com/iruri/ex/vo/BoardVO.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/views/challenge/challenge_detail_after.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_before.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_make_form.jsp, src/main/webapp/resources/src/js/challenge/c_modal.js
- 210808-상세페이지 댓글입력(하는중), 챌린지 참여하기(하는중)
- 210808-상세페이지 댓글입력(하는중), 챌린지 참여하기(하는중)
- 내용을 적어주세요.
=> 210808-상세페이지 댓글입력(하는중), 챌린지 참여하기(하는중)

pom.xml, src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/service/ChallengeService.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/java/com/iruri/ex/vo/BoardVO.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/challenge/challenge_detail_after.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_before.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_main2.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_make_form.jsp, src/main/webapp/WEB-INF/views/include/static.jsp, src/main/webapp/WEB-INF/web.xml, src/main/webapp/resources/src/css/page/c_detail_before_styles.css, src/main/webapp/resources/src/js/challenge/c_modal.js
- 210809-파일업로드, 상세페이지 댓글입력 ajax, 챌린지 참여하면 기록 남기기
- 210809-파일업로드, 상세페이지 댓글입력 ajax, 챌린지 참여하면 기록 남기기
- 내용을 적어주세요.
=> 210809-파일업로드, 상세페이지 댓글입력 ajax, 챌린지 참여하면 기록 남기기

src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/controller/ImageController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/service/ChallengeService.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/views/challenge/challenge_detail_after.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_before.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_make_form.jsp, src/main/webapp/resources/src/css/page/c_detail_after_styles.css, src/main/webapp/resources/src/css/page/c_detail_before_styles.css, src/main/webapp/resources/src/js/challenge/c_modal.js, src/main/webapp/resources/src/js/challenge/c_sticky.js
- 210810 - 인증글 사진 한글파일명, 인증글 사진 띄우기
- 210810 - 인증글 사진 한글파일명, 인증글 사진 띄우기
- 내용을 적어주세요.
=> 210810 - 인증글 사진 한글파일명, 인증글 사진 띄우기

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/java/com/iruri/ex/mapper/UserChallengeMapper.java, src/main/java/com/iruri/ex/service/UserChallengeService.java, src/main/java/com/iruri/ex/service/UserChallengeServiceImpl.java, src/main/java/com/iruri/ex/vo/BoardVO.java, src/main/resources/com/iruri/ex/mapper/UserChallengeMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_challengelist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_classlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_pointlist.jsp, src/main/webapp/resources/src/css/page/mypage_user_challengelist.css, src/main/webapp/resources/src/css/page/mypage_user_class.css, src/main/webapp/resources/src/css/page/mypage_user_modal.css, src/main/webapp/resources/src/css/page/mypage_user_pointlist.css, src/main/webapp/resources/src/js/mypage_user_main.js
0811 챌린지 취소 완료
- 내용을 적어주세요.
- 내용을 적어주세요.
=> 0803 mypage user

src/main/java/com/iruri/ex/controller/ChallengeController.java, src/main/java/com/iruri/ex/mapper/ChallengeMapper.java, src/main/java/com/iruri/ex/service/ChallengeService.java, src/main/java/com/iruri/ex/service/ChallengeServiceImpl.java, src/main/resources/com/iruri/ex/mapper/ChallengeMapper.xml, src/main/webapp/WEB-INF/views/challenge/challenge_LikeList.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_detail_after.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_endList.jsp, src/main/webapp/WEB-INF/views/challenge/challenge_main2.jsp, src/main/webapp/resources/src/css/page/c_main_styles.css, src/main/webapp/resources/src/js/challenge/c_modal.js
- 210812 - 추천챌린지(인기순상위2개)띄우기, 인증사진 삭제하기, 댓글 수정하기
- 210812 - 추천챌린지(인기순상위2개)띄우기, 인증사진 삭제하기, 댓글 수정하기
- 내용을 적어주세요.
=> 210812 - 추천챌린지(인기순상위2개)띄우기, 인증사진 삭제하기, 댓글 수정하기

src/main/java/com/iruri/ex/controller/MypageTrainerController.java, src/main/java/com/iruri/ex/mapper/MypageTrainerMapper.java, src/main/java/com/iruri/ex/service/MypageTrainerService.java, src/main/java/com/iruri/ex/service/MypageTrainerServiceImpl.java, src/main/java/com/iruri/ex/vo/ICommentVO.java, src/main/java/com/iruri/ex/vo/TableJoinVO.java, src/main/resources/com/iruri/ex/mapper/MypageTrainerMapper.xml, src/main/webapp/WEB-INF/views/mypage_trainer/mypage_trainer_class_make.jsp, src/main/webapp/WEB-INF/views/mypage_trainer/mypage_trainer_main.jsp, src/main/webapp/WEB-INF/views/mypage_trainer/mypage_trainer_user_management.jsp, src/main/webapp/WEB-INF/views/mypage_trainer/mypage_trainer_user_management2(나중에지우기).jsp
- 내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> 회원관리.. 모태여..

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/java/com/iruri/ex/mapper/BoardMapper.java, src/main/java/com/iruri/ex/mapper/IUserInfoMapper.java, src/main/java/com/iruri/ex/service/BoardService.java, src/main/java/com/iruri/ex/service/BoardServiceImpl.java, src/main/java/com/iruri/ex/service/IUserInfoService.java, src/main/java/com/iruri/ex/service/IUserInfoServleImpl.java, src/main/resources/com/iruri/ex/mapper/BoardMapper.xml, src/main/resources/com/iruri/ex/mapper/IUserInfoMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_boardlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_pointlist.jsp, src/main/webapp/resources/src/css/page/mypage_user_main.css
mypage_user 클래스로 링크랑 board에서 댓글링크 빼고 완료
- 내용을 적어주세요.
- 내용을 적어주세요.
=> mypage_user 클래스로 링크랑 board에서 댓글링크 빼고 완료

src/main/java/com/iruri/ex/controller/MypageUserController.java, src/main/webapp/WEB-INF/views/iruritip/iruritip_boardwrite.jsp, src/main/webapp/WEB-INF/views/iruritip/iruritip_freeboard.jsp, src/main/webapp/WEB-INF/views/iruritip/iruritip_main.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_boardlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_challengelist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_classlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_main.jsp, src/main/webapp/resources/src/css/page/iruritip_main.css
iruritip_main, 이루리팁게시판list, 이루리팁게시판에글쓰기 html
- 내용을 적어주세요.
- 내용을 적어주세요.
=> iruritip_main, 이루리팁게시판list, 이루리팁게시판에글쓰기 html

src/main/java/com/iruri/ex/service/IUserInfoServleImpl.java, src/main/java/com/iruri/ex/service/PointServiceImpl.java, src/main/resources/com/iruri/ex/mapper/IUserInfoMapper.xml, src/main/resources/com/iruri/ex/mapper/PointMapper.xml, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_boardlist.jsp, src/main/webapp/WEB-INF/views/mypage_user/mypage_user_classlist.jsp, src/main/webapp/WEB-INF/views/ptclass/ptclass_details.jsp, src/main/webapp/resources/src/css/iruri_tip/iruri_ex_video_detail.css, src/main/webapp/resources/src/css/page/ptClassDetails.css
mypage_user 수정 완
- 내용을 적어주세요.
- 내용을 적어주세요.
=> mypage_user 수정 완
